# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Huy Xuan Pham
title: PhD candidate in Robotics
email: phxhuy@gmail.com
website: https://phxhuy.github.io./

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  phxhuy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: huyxuanpham
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=lDuf0tAAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/HuyPham.png
about_content: | # this will include new lines to allow paragraphs
  I am a Robotics researcher in Autonomous navigation and motion planning for mobile robots. I have experience in building robots from scratch to a full-autonomy system.

  My research topics are Autonomous Motion Planning and Navigation, Deep Learning for Robotics, Computer Vision, and Multi-Robot Systems.

  I am most skilled in: <mark>C++</mark>, <mark>python</mark>, <mark>ROS</mark>, <mark>tensorflow</mark>, <mark>pytorch</mark> and <mark>Board Games</mark>

content:
  - title: Featured Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # - layout: top-middle
      - layout: top-middle
        title: Event-based Navigation for Autonomous Drone Racing with Sparse Gated Recurrent Network 
        # link_text: Project Website
        additional_links:
          - title:  open-airlab/GateNet
            icon: fab fa-github
            url: https://github.com/open-airlab/GateNet
            
        quote: >
          Can robots learn more efficient? The answer may come from novel neuromorphic cameras.
          
        description: | # this will include new lines to allow paragraphs
          <img style="float: left;" src="images/event_process.png"> 
          
          Together with my MS student Kristoffer Andersen, I propose an autonomous drone system that leverages an event-based camera and a novel deep learning architecture based on gated recurrent units and sparse convolutions to effectively perceive racing gates in difficult visual conditions at very high speeds and low illumination.
          We also prove that the sim-to-real transfer learning scheme significantly improves the accuracy of the robot's perception module.
          [Link video](https://youtu.be/aFhtpOzczrc)

      - layout: top-middle
        title: GateNet - An Efficient Deep Neural Network Architecture for Gate Perception Using Fish-Eye Camera in Autonomous Drone Racing
        link: https://github.com/open-airlab/GateNet
        # link_text: Project Website
        additional_links:
          - title:  open-airlab/GateNet
            icon: fab fa-github
            url: https://github.com/open-airlab/GateNet
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Can an agile racing drone senses a gate in very close environment with one single RGB camera? Yes! I built an entire hardware system and software pipeline to prove it.
          
        description: | # this will include new lines to allow paragraphs
          <img style="float: left;" src="images/drone_racing.png"> 
          
          I propose a convolutional neural network-based gate detector for drone racing (GateNet) that concurrently detects gate’s center, distance, and orientation with respect to the drone using only images from a single fish-eye RGB camera. GateNet achieves a high inference rate (up to 60Hz) on an onboard processor (Jetson TX2). Moreover, GateNet is robust to gate pose changes and background disturbances. The proposed perception pipeline leverages a fish-eye lens with a wide field-of-view and thus can detect multiple gates in close range, allowing a longer planning horizon even in tight environments.
          I implement a geometric controller to control the drone and an optimization-based minimum-snap trajectory generation method for local motion planning.
          [Link video](https://youtu.be/sTO85tEDtE8)

      - layout: top-middle
        title: Localization for autonomous car in GPS-denied environments
        # link: https://github.com/open-airlab/GateNet
        # link_text: Project Website
        # additional_links:
        #   - title:  open-airlab/GateNet
        #     icon: fab fa-github
        #     url: https://github.com/open-airlab/GateNet
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          How can an autonomous car navigate in a GPS-denied environment? Visual-inertial odometry is the key.
        description: | # this will include new lines to allow paragraphs
          <img style="float: left;" src="images/autonomos_car.png"> 

          In this work, I engineer a visual-inertial odometry framework that composes of multiple IMU-camera systems and sensor fusion to enable an autonomous car drive independent of GPS and other external localization sources. The system runs an enhanced version of the Robust Visual Inertial Odometry ([Rovio](https://github.com/ethz-asl/rovio)) to robustly navigate the environment using only local information capturing from the cameras and ego-motion estimation from IMUs.
          
          [Link video](https://youtu.be/PzgActp3Gok)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AiR Lab, Aarhus University, Denmark
        link: https://ece.au.dk/en/research/key-areas-in-research-and-development/communication-control-and-automation/artificial-intelligence-in-robotics/
        # link_text: boringcompany.com
        sub_title: PhD student
        caption: September 2019 - Present
        quote: >
          Solving autonomous navigation for agile robotic systems
        description: | # this will include new lines to allow paragraphs
            My goal is to re-innovate autonomous navigation and motion planning for robot systems with the help of Deep Learning. My research involves developing novel software and algorithms, occasionally also engineering new robot platforms, for agile quadrotors, equipped with visual sensors and small onboard computers flying at high speed in challenging scenarios. Potential applications could be Autonomous Drone Racing, Search and Rescues, and reconnaissance missions in dynamic or unstructured environments.
      
      - layout: left
        title:  Autonomous Robots Lab (ARL), University of Nevada, Reno, USA
        link:  https://www.autonomousrobotslab.com/      # link_text: boringcompany.com
        sub_title: Research Engineer
        caption: December 2018 - September 2019
        quote: >
          Design localization system and path planning for ground an aerial robotic systems.
        description: | # this will include new lines to allow paragraphs
            Solving engineering and research problems for my team in multiple projects. I have the honor to participate in the <mark>DARPA SubT challenge</mark> with my team during this time.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Aarhus University, Denmark
        caption: 2019 - 2022
        sub_title: PhD in Robotics
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Doing my Ph.D. at Aarhus University, Denmark is one of the best experiences I have ever had. Here I have the opportunities to work with talented researchers in a world-class facility and a supportive environment. During this time I have developed my skills and attitude to be an independent researcher and thinker, capable of leading my research projects and, in the future, my own lab.

      - layout: left
        title: University of Nevada, Reno, USA
        caption: 2017 - 2019
        sub_title: Master's degree in Computer Science
        
        description: | # this will include new lines to allow paragraphs
          This is the place where I have learned Robotics! As a research assistant and later a lab engineer, I have worked on a few projects in different labs. I have worked with state-of-the-art path planning and state estimation frameworks for both aerial robots and ground robots, from individual missions to collaborative team missions. I have used both model-based and model-free methods for my work, and the knowledge and skills I have acquired during this time are essential for my career.

      - layout: left
        title: University of Oklahoma, Norman, USA
        caption: 2013 - 2015
        sub_title: Master's degree in Industrial and System Engineering

        description: | # this will include new lines to allow paragraphs
          I came to the university under a prestigious US government scholarship, the Vietnam Education Foundation (VEF), to study Industrial and System Engineering. I managed to do well in this new horizon and acquired valuable experiences, particularly in solving convex and non-convex optimization problems, that I still rely upon today. 


      - layout: left
        title: Hanoi University of Science and Technology, Hanoi, Vietnam
        caption: 2006 - 2011
        sub_title: Bachelor of Engineering in Automation and Control Engineering

        description: | # this will include new lines to allow paragraphs
          I am graduated from one of the top technical universities in Vietnam. Here I have learned the basics of maths, physics, programming, and even some research skills. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Robotics and software engineering some of my other interests and hobbies are:
      - Building and racing drones!
      - Biking
      - Hiking
      - Football
      - Board games

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
