# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Huy Xuan Pham
title: PhD candidate in Robotics
email: phxhuy@gmail.com
website: https://phxhuy.github.io./

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  phxhuy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: huyxuanpham
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: https://www.youtube.com/channel/UCZIkvuSlrpEh4C2oduQIGXg
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/HuyPham.png
about_content: | # this will include new lines to allow paragraphs
  I am a Robotics researcher in Autonomous navigation and motion planning for mobile robots. I have experience in building robots from scratch to a full autonomy system.

  I am most skilled in: <mark>C++</mark>, <mark>python</mark>, <mark>ROS</mark> and <mark>Board Games</mark>

content:
  - title: Featured Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # - layout: top-middle
      - layout: top-middle
        title: GateNet - An Efficient Deep Neural Network Architecture for Gate Perception Using Fish-Eye Camera in Autonomous Drone Racing
        link: https://github.com/open-airlab/GateNet
        # link_text: Project Website
        additional_links:
          - title:  open-airlab/GateNet
            icon: fab fa-github
            url: https://github.com/open-airlab/GateNet
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Can an agile racing drone senses a gate in very close environment with one single RGB camera? Yes it can.
        description: | # this will include new lines to allow paragraphs
          We propose a convolutional neural network-based gate detector (GateNet) that concurrently detects gate’s center, distance, and orientation with respect to the drone using only images from a single fish-eye RGB camera. GateNet achieves a high inference rate (up to 60Hz) on an onboard processor (Jetson TX2). Moreover, GateNet is robust to gate pose changes and background disturbances. The proposed perception pipeline leverages a fish-eye lens with a wide field-of-view and thus can detect multiple gates in close range, allowing a longer planning horizon even in tight environments.
          
          ![drone racing](images/drone_racing.jpg "Autonomous Drone Racing")
    - layout: top-middle
            title: Localization for autonomous car in GPS-denied environment
            # link: https://github.com/open-airlab/GateNet
            # link_text: Project Website
            # additional_links:
            #   - title:  open-airlab/GateNet
            #     icon: fab fa-github
            #     url: https://github.com/open-airlab/GateNet
              # - title:  Github page for project (eg. sproogen/modern-resume-theme)
              #   icon: fab fa-github
              #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
            quote: >
              How can an autonomous car navigate in a GPS-denied environment? Visual-inertial odometry is the key.
            description: | # this will include new lines to allow paragraphs
              In this work we engineered a Visual-inertial odometry system that composes of multiple IMU-camera systems and sensor fusion to enable an autonomous car drives independent of GPS and other external localization system. The system runs an enhanced version of Robust Visual Inertial Odometry ((Rovio)[https://github.com/ethz-asl/rovio]) enable the car to robustly navigate the environment using only local information.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AiR Lab, Aarhus University, Denmark
        link: https://ece.au.dk/en/research/key-areas-in-research-and-development/communication-control-and-automation/artificial-intelligence-in-robotics/
        # link_text: boringcompany.com
        sub_title: PhD student
        caption: September 2019 - Present
        quote: >
          Solving autonomous navigation for agile robotic systems
        description: | # this will include new lines to allow paragraphs
            My goal is to re-innovate autonomous path planning and navigation with the help of Machine Learning, Deep Learning, and advanced Computer Vision technologies in perception and state estimation. My research involves developing novel software and algorithms, occasionally engineering new platforms, for light-weight quadrotors, equipped with visual sensors and small onboard computers while flying at high-speed in challenging scenarios. Potential applications could be in Autonomous Drone Racing, Search and Rescues, and reconnaissance missions in dynamic or unstructured environments.
      
      - layout: left
        title:  Autonomous Robots Lab (ARL), University of Nevada, Reno, USA
        link:  https://www.autonomousrobotslab.com/modeling.html       # link_text: boringcompany.com
        sub_title: Research Engineer
        caption: December 2018 - September 2019
        quote: >
          Design localization system and path planning for ground an aerial robotic systems.
        description: | # this will include new lines to allow paragraphs
            Solving engineering and research problems for my team in multiple projects. I have the honor to participate the <mark>DARPA SubT challenge</mark> with my team during this time.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Aarhus University, Denmark
        caption: 2019 - 2022
        sub_title: PhD in Robotics
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      
      - layout: left
        title: University of Nevada, Reno, USA
        caption: 2017 - 2019
        sub_title: Master's degree in Computer Science

      - layout: left
        title: University of Oklahoma, Norman, USA
        caption: 2013 - 2015
        sub_title: Master's degree in Industrial and System Engineering


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Robotics and software engineering some of my other interests and hobbies are:
      - Biking
      - Hiking
      - Football
      - Board games

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
